apps/datul/urls.py
from django.urls import path, re_path

from . import views


app_name = 'datul'
urlpatterns = [
    # path('', views.index, name='index'),
    re_path(r'^peserta/$',
            views.PesertaListView.as_view(), name='peserta_list'),
    re_path(r'^peserta/(?P<pk>[0-9]+)/$',
            views.PesertaRowView.as_view()),
    re_path(r'^peserta/status/(?P<status>[0-9]+)/$',
            views.PesertaStatusView.as_view()),
    re_path(r'^pmp/$',
            views.PMPListView.as_view(), name='pmp_list'),
    re_path(r'^pmp/(?P<pk>[0-9]+)/$',
            views.PMPRowView.as_view()),
    re_path(r'^provinsi/$',
            views.ProvinsiListView.as_view(), name='prov_list'),
    re_path(r'^provinsi/(?P<pk>[0-9]+)/$',
            views.ProvinsiRowView.as_view()),
    re_path(r'^daerah/$',
            views.DaerahListView.as_view(), name='drh_list'),
    re_path(r'^daerah/(?P<pk>[0-9]+)/$',
            views.DaerahRowView.as_view()),
    re_path(r'^daerah/prov/(?P<id_prov>[0-9]+)/$',
            views.DaerahProvView.as_view()),
    re_path(r'^daerah/kota/(?P<kota>[\w+\+?]+)/$',
            views.DaerahKotaView.as_view()),
    re_path(r'^daerah/camat/(?P<camat>[\w+\+?]+)/$',
            views.DaerahCamatView.as_view()),
    re_path(r'^daerah/desa/(?P<desa>[\w+\+?]+)/$',
            views.DaerahDesaView.as_view()),
    re_path(r'^daerah/pos/(?P<pos>\w+)/$',
            views.DaerahPostalView.as_view()),
    re_path(r'^p2tel/$',
            views.P2TELListView.as_view(), name='p2tel_list'),
    re_path(r'^p2tel/(?P<pk>[0-9]+)/$',
            views.P2TELRowView.as_view()),
]

apps/info/urls.py
from django.urls import path

from . import views


app_name = 'info'
urlpatterns = [
    path('', views.index, name='index'),
]

apps/users/urls.py
from django.urls import path, re_path
from rest_framework_jwt.views import refresh_jwt_token
from .views import RegisterUsersView, LoginView, UserView, UserNameView

app_name = 'user'
urlpatterns = [
    path('api-token-refresh/', refresh_jwt_token, name='new_token'),
    path('auth/login/', LoginView.as_view(), name='user_login'),
    path('auth/register/', RegisterUsersView.as_view(), name='user_regis'),
    re_path(r'^user/(?P<nik>\w+)/$',
            UserView.as_view()),
    re_path(r'^user/id/(?P<username>\w+)/$',
            UserNameView.as_view()),
    # path('songs/', ListSongsView.as_view(), name="songs-all")
]

simpul_api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.info.urls')),
    path('api/', include('apps.users.urls')),
    path('api/', include('apps.datul.urls')),
]

apps/datul/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.db import models


class Provinsi(models.Model):
    nama_provinsi = models.CharField(max_length=50)

    def __str__(self):
        return self.nama_provinsi


class Daerah(models.Model):
    kelurahan = models.CharField(max_length=50)
    kecamatan = models.CharField(max_length=50)
    kota = models.CharField(max_length=50)
    provinsi = models.ForeignKey(
        Provinsi,
        on_delete=models.CASCADE,
    )
    kode_pos = models.CharField(max_length=10)

    def __str__(self):
        return self.kelurahan


class P2TEL(models.Model):
    nama_pc = models.CharField(max_length=100)
    user_pc = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    alamat = models.TextField()
    Kontak = models.TextField()

    def __str__(self):
        return self.nama_pc


class P2TEL_Wilayah(models.Model):
    id_p2tel = models.ForeignKey(
        P2TEL,
        on_delete=models.CASCADE,
    )
    id_daerah = models.ForeignKey(
        Daerah,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.id_p2tel + ' ' + self.id_daerah


class Peserta(models.Model):
    nik = models.CharField(max_length=10)
    nama = models.CharField(max_length=100)
    p2tel = models.ForeignKey(
        P2TEL,
        on_delete=models.CASCADE,
    )
    status = models.CharField(max_length=50)
    penyebab = models.CharField(max_length=100)
    tanggal_penyebab = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.nik


class P2TEL_Member(models.Model):
    peserta = models.ForeignKey(
        Peserta,
        on_delete=models.CASCADE,
    )
    jabatan = models.CharField(max_length=20)

    def __str__(self):
        return self.peserta


class PMP(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    peserta = models.ForeignKey(
        Peserta,
        on_delete=models.CASCADE,
    )
    id_p2tel = models.ForeignKey(
        P2TEL,
        on_delete=models.CASCADE,
    )
    nama = models.CharField(max_length=100)
    awn = models.SmallIntegerField()
    hubungan = models.CharField(max_length=50, blank=True)
    status_hidup = models.BooleanField()
    ktp = models.CharField(max_length=20, blank=True)
    npwp = models.CharField(max_length=20, blank=True)
    agama = models.CharField(max_length=20, blank=True)
    goldar = models.CharField(max_length=5, blank=True)
    jk = models.CharField(max_length=5)
    tempat_lahir = models.CharField(max_length=50)
    tanggal_lahir = models.DateField()
    jalan = models.CharField(max_length=100, blank=True)
    komplek = models.CharField(max_length=100, blank=True)
    blok = models.CharField(max_length=20, blank=True)
    no = models.CharField(max_length=20, blank=True)
    rt = models.CharField(max_length=20, blank=True)
    rw = models.CharField(max_length=20, blank=True)
    provinsi = models.CharField(max_length=50, blank=True)
    kota = models.CharField(max_length=50, blank=True)
    kecamatan = models.CharField(max_length=50, blank=True)
    kelurahan = models.CharField(max_length=50, blank=True)
    kodepos = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.nama


class Kontak(models.Model):
    pmp = models.ForeignKey(
        PMP,
        on_delete=models.CASCADE,
    )
    kontak = models.CharField(max_length=100)

    def __str__(self):
        return self.kontak


class Datul(models.Model):
    peserta = models.ForeignKey(
        Peserta,
        on_delete=models.CASCADE,
    )
    user_pendatul = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    tanggal_datul = models.DateField()
    tanggal_silaturahim = models.DateField()
    jenis_silaturahim = models.CharField(max_length=20)
    catatan_datul = models.TextField()

    def __str__(self):
        return self.peserta


class Dokumen(models.Model):
    id_datul = models.ForeignKey(
        Datul,
        on_delete=models.CASCADE,
    )
    detail = models.TextField()
    file = models.FileField()

    def __str__(self):
        return self.detail


class PMP_Temp(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    peserta = models.ForeignKey(
        Peserta,
        on_delete=models.CASCADE,
    )
    id_p2tel = models.ForeignKey(
        P2TEL,
        on_delete=models.CASCADE,
    )
    nama = models.CharField(max_length=100)
    awn = models.SmallIntegerField()
    hubungan = models.CharField(max_length=50, blank=True)
    status_hidup = models.BooleanField()
    ktp = models.CharField(max_length=20, blank=True)
    npwp = models.CharField(max_length=20, blank=True)
    agama = models.CharField(max_length=20, blank=True)
    goldar = models.CharField(max_length=5, blank=True)
    jk = models.CharField(max_length=5)
    tempat_lahir = models.CharField(max_length=50)
    tanggal_lahir = models.DateField()
    jalan = models.CharField(max_length=100, blank=True)
    komplek = models.CharField(max_length=100, blank=True)
    blok = models.CharField(max_length=20, blank=True)
    no = models.CharField(max_length=20, blank=True)
    rt = models.CharField(max_length=20, blank=True)
    rw = models.CharField(max_length=20, blank=True)
    provinsi = models.CharField(max_length=50, blank=True)
    kota = models.CharField(max_length=50, blank=True)
    kecamatan = models.CharField(max_length=50, blank=True)
    kelurahan = models.CharField(max_length=50, blank=True)
    kodepos = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.user

apps/info/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.db import models


class Berita(models.Model):
    user_penulis = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        )
    waktu = models.DateTimeField()
    judul = models.CharField(max_length=100)
    isi = models.TextField()

    def __str__(self):
        return self.judul

    class Meta:
        ordering = ('waktu',)


class Info(models.Model):
    foto_info = models.ImageField()
    grup_tujuan = models.ManyToManyField(Group,)


class Data_History(models.Model):
    user = models.CharField(max_length=150)
    aksi = models.CharField(max_length=20)
    detail = models.TextField()

    def __str__(self):
        return self.user + ' ' + self.aksi

apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    nik = models.CharField(max_length=10, blank=True)
    foto_profil = models.TextField(blank=True)

    first_name = None
    last_name = None

    def __str__(self):
        return self.username

apps/users/forms.py
# users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

apps/info/views.py
from django.shortcuts import render


def index(request):
    # TODO change this url to your hostname
    context = {
        'current_site': "https://simpul.pythonanywhere.com"
    }
    return render(request, 'info/index.html', context)

apps/users/views.py
from datetime import datetime

from django.contrib.auth import authenticate, login
from django.contrib.auth import get_user_model
from rest_framework import generics, permissions, status
from rest_framework.response import Response
from rest_framework_jwt.settings import api_settings

from .serializers import TokenSerializer, RegisterSerializer, UserSerializer

from apps.datul.models import Kontak, PMP

jwt_payload_handler = api_settings.JWT_PAYLOAD_HANDLER
jwt_encode_handler = api_settings.JWT_ENCODE_HANDLER
User = get_user_model()


class LoginView(generics.CreateAPIView):
    """
    POST auth/login/
    """
    # This permission class will overide the global permission
    # class setting
    permission_classes = (permissions.AllowAny,)
    http_method_names = ['post', ]

    def post(self, request, *args, **kwargs):
        nik = request.data.get("nik", "")
        tanggal_lahir = request.data.get("tanggal_lahir", "")
        username = nik + '_' + tanggal_lahir
        password = request.data.get("password", "")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            # login saves the user’s ID in the session,
            # using Django’s session framework.
            login(request, user)
            serializer = TokenSerializer(data={
                # using drf jwt utility functions to generate a token
                "token": jwt_encode_handler(
                    jwt_payload_handler(user)
                )})
            serializer.is_valid()
            return Response(serializer.data)
        else:
            return Response(
                data={
                    "message": "username or password is wrong"
                },
                status=status.HTTP_400_BAD_REQUEST
            )
        return Response(status=status.HTTP_401_UNAUTHORIZED)


class RegisterUsersView(generics.CreateAPIView):
    """
    POST auth/register/
    """
    permission_classes = (permissions.AllowAny,)
    http_method_names = ['post', ]

    def post(self, request, *args, **kwargs):
        serializer = RegisterSerializer(
            data=request.data
        )
        nik = request.data.get('nik', '')
        password = request.data.get('password', '')
        tanggal_lahir = request.data.get('tanggal_lahir', '00000000')
        email = request.data.get('email', '')
        kontak_hp = request.data.get('kontak', '')

        username = nik + '_' + tanggal_lahir
        if serializer.is_valid(raise_exception=True):
            tl = datetime.strptime(tanggal_lahir, '%d%m%Y')
            pmps = PMP.objects.filter(
                peserta__nik=nik,
            )
            if not pmps:
                return Response(
                    data={
                        "message": "username or tanggal_lahir invalid"
                    },
                    status=status.HTTP_400_BAD_REQUEST
                )
            for pmp in pmps:
                if pmp.tanggal_lahir == tl.date():
                    if not pmp.user:
                        new_user = User.objects.create_user(
                            username=username,
                            password=password,
                            email=email,
                            nik=nik,
                        )
                        user = User.objects.get(id=new_user.id)
                        pmp.user = user
                        pmp.save()
                        Kontak.objects.create(
                            kontak=kontak_hp,
                            pmp=pmp
                        )
                        return Response(status=status.HTTP_201_CREATED)
            mess = "account already exist, or pmp is not registered"
            return Response(
                data={
                    "message": mess
                },
                status=status.HTTP_400_BAD_REQUEST
            )
        return Response(
            data={
                serializer.errors
            },
            status=status.HTTP_400_BAD_REQUEST
        )


class UserView(generics.ListAPIView):
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = UserSerializer

    def get_queryset(self):
        nik = self.kwargs['nik']
        return User.objects.filter(nik=nik)


class UserNameView(generics.ListAPIView):
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = UserSerializer

    def get_queryset(self):
        username = self.kwargs['username']
        return User.objects.filter(username=username)

apps/info/templates/info/model/auth.html
<h4>
    <li><a name='Auth'></a>Authentication</li>
</h4>
<p>Auth yang disediakan saat ini hanya untuk pmp saja
    . Auth untuk akun yang lain sedang dalam proses pengerjaan
    <br>
    Untuk Akses Admin, kunjungi <a href="{{ current_site }}/admin">{{ current_site }}/admin</a></p>
<ol type="a">
    <li>Register</li>
    <ul>
        <li>POST method <a href='#Auth'>{{ current_site }}{% url "user:user_regis" %}</a></li>
        <p>body param : nik, password, password2, tanggal_lahir(ddmmyyyy), email*, kontak</p>
        <p>success return : STATUS 201</p>
        <p>NIK dan tanggal lahir harus sesuai dengan yang ada pada tabel datul_pmp</p>
    </ul>
    <li>Login</li>
    <ul>
        <li>POST method <a href='#Auth'>{{ current_site }}{% url "user:user_login" %}</a></li>
        <p>body param : nik, password, tanggal_lahir</p>
        <p>success return : STATUS 200, token</p>
    </ul>
    <li>Refresh Token</li>
    Token yang didapat dari Login hanya bertahan selama 1 jam. Minta token baru di menit-menit akhir dengan metode ini
    <ul>
        <li>POST method <a href='#Auth'>{{ current_site }}{% url "user:new_token" %}</a></li>
        <p>body param : token (token lama)</p>
        <p>success return : STATUS 200, token (token baru)</p>
    </ul>
    Setelah mendapatkan Token baru, token lama dapat diabaikan. Jika Refresh gagal karena token expire, maka invoke
    user untuk login kembali
</ol>

apps/info/templates/info/model/daerah.html
<h4>
    <li><a name='Daerah'></a>Model Daerah</li>
</h4>
<p>Model Daerah Berisi daerah dari tingkat kota-kelurahan + kode pos</p>
<ol type="a">
    <li>Get by ID</li>
    <ul>
        <li>GET method <a href='#Daerah'>{{ current_site }}{% url "datul:drh_list" %}1/</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token) </p>
        <p>success return : STATUS 200, daerah</p>
    </ul>
    <li>Get by Provinsi</li>
    <ul>
        <li>GET method <a href='#Daerah'>{{ current_site }}{% url "datul:drh_list" %}prov/11/</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token) </p>
        <p>success return : STATUS 200, list(daerah)</p>
    </ul>
    <li>Get by Kota</li>
    <ul>
        <li>GET method <a href='#Daerah'>{{ current_site }}{% url "datul:drh_list" %}kota/PIDIE+JAYA/</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token) </p>
        <p>success return : STATUS 200, list(daerah)</p>
    </ul>
    <li>Get by Kecamatan</li>
    <ul>
        <li>GET method <a href='#Daerah'>{{ current_site }}{% url "datul:drh_list" %}camat/BANDAR+BARU/</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token) </p>
        <p>success return : STATUS 200, list(daerah)</p>
    </ul>
    <li>Get by Kelurahan</li>
    <ul>
        <li>GET method <a href='#Daerah'>{{ current_site }}{% url "datul:drh_list" %}desa/ABAH+LUENG/</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token) </p>
        <p>success return : STATUS 200, daerah</p>
    </ul>
    <li>Get by Postal Code</li>
    <ul>
        <li>GET method <a href='#Daerah'>{{ current_site }}{% url "datul:drh_list" %}pos/24184/</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token) </p>
        <p>success return : STATUS 200, list(daerah)</p>
    </ul>
</ol>

apps/info/templates/info/model/p2tel.html
<h4>
    <li><a name='P2tel'></a>Model P2TEL</li>
</h4>
<ol type="a">
    <li>Get ALL</li>
    <ul>
        <li>GET method <a href='#P2tel'>{{ current_site }}{% url "datul:p2tel_list" %}</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token) </p>
        <p>success return : STATUS 200, list(p2tel)</p>
    </ul>
    <li>Get by ID</li>
    <ul>
        <li>GET method <a href='#P2tel'>{{ current_site }}{% url "datul:p2tel_list" %}1/</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token) </p>
        <p>success return : STATUS 200, peserta</p>
    </ul>
</ol>

apps/info/templates/info/model/peserta.html
<h4>
    <li><a name='Peserta'></a>Model Peserta</li>
</h4>
<p>Model ini berisi data Peserta Datul</p>
<ol type="a">
    <li>Get ALL</li>
    <ul>
        <li>GET method <a href='#Peserta'>{{ current_site }}{% url "datul:peserta_list" %}</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token) </p>
        <p>success return : STATUS 200, list(peserta)</p>
    </ul>
    <li>Get by ID</li>
    <ul>
        <li>GET method <a href='#Peserta'>{{ current_site }}{% url "datul:peserta_list" %}1/</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token) </p>
        <p>success return : STATUS 200, peserta</p>
    </ul>
    <li>Get by Status</li>
    <p>
        keterangan status peserta<br>
        0 = tidak wajib datul<br>
        1 = belum datul<br>
        2 = menunggu konfirmasi<br>
        3 = sudah datul<br>
        4 = selesai datul<br>
        5 = pmp baru<br>
    </p>
    <ul>
        <li>GET method <a href='#Peserta'>{{ current_site }}{% url "datul:peserta_list" %}status/0/</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token) </p>
        <p>success return : STATUS 200, list(peserta)</p>
    </ul>
</ol>

apps/info/templates/info/model/pmp.html
<h4>
    <li><a name='Pmp'></a>Model PMP</li>
</h4>
<ol type="a">
    <li>Get ALL</li>
    <ul>
        <li>GET method <a href='#PMP'>{{ current_site }}{% url "datul:pmp_list" %}</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token) </p>
        <p>success return : STATUS 200, list(peserta)</p>
    </ul>
    <li>Get by ID</li>
    <ul>
        <li>GET method <a href='#PMP'>{{ current_site }}{% url "datul:pmp_list" %}1/</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token) </p>
        <p>success return : STATUS 200, peserta</p>
    </ul>
</ol>

apps/info/templates/info/model/provinsi.html
<h4>
    <li><a name='Provinsi'></a>Model Provinsi</li>
</h4>
<ol type="a">
    <li>Get ALL</li>
    <ul>
        <li>GET method <a href='#Provinsi'>{{ current_site }}{% url "datul:prov_list" %}</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token) </p>
        <p>success return : STATUS 200, list(provinsi)</p>
    </ul>
    <li>Get by ID</li>
    <ul>
        <li>GET method <a href='#Provinsi'>{{ current_site }}{% url "datul:prov_list" %}1/</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token) </p>
        <p>success return : STATUS 200, provinsi</p>
    </ul>
</ol>

apps/info/templates/info/model/user.html
<h4>
    <li><a name='User'></a>Model User</li>
</h4>
<p>Foto Profil disimpan di Model USER</p>
<ol type="a">
    <li>Get by nik</li>
    <ul>
        <li>GET method <a href='#User'>{{ current_site }}/api/user/123456/</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token)</p>
        <p>success return : STATUS 200, user</p>
    </ul>
    <li>Get by username</li>
    <ul>
        <p>Ada Beberapa akun yang tidak memiliki nik, maka gunakan usernamenya</p>
        <li>GET method <a href='#User'>{{ current_site }}/api/user/id/admin/</a></li>
        <p>header param : Authorization ('Bearer' + '&lt;spasi&gt;' + token)</p>
        <p>success return : STATUS 200, user</p>
    </ul>
</ol>