apps/info/urls.py
from django.urls import path

from . import views


app_name = 'info'
urlpatterns = [
    path('', views.index, name='index'),
]

simpul_api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.info.urls')),
    path('api/', include('apps.users.urls')),
    path('api/', include('apps.datul.urls')),
]

apps/info/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.db import models


class Berita(models.Model):
    user_penulis = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        )
    waktu = models.DateTimeField()
    judul = models.CharField(max_length=100)
    isi = models.TextField()

    def __str__(self):
        return self.judul

    class Meta:
        ordering = ('waktu',)


class Info(models.Model):
    foto_info = models.ImageField()
    grup_tujuan = models.ManyToManyField(Group,)


class Data_History(models.Model):
    user = models.CharField(max_length=150)
    aksi = models.CharField(max_length=20)
    detail = models.TextField()

    def __str__(self):
        return self.user + ' ' + self.aksi

apps/info/views.py
from django.shortcuts import render


def index(request):
    # TODO change this url to your hostname
    context = {
        'current_site': "https://simpul.pythonanywhere.com"
    }
    return render(request, 'info/index.html', context)

apps/info/templates/info/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    {% include 'info/layout/header.html' %}
    {% block extra_style %}{% endblock %}
</head>
<body>
<!-- Include Navbar -->
{% include 'info/layout/navbar.html' %}
<!-- Page Content -->
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-12">
                <br>
        <!-- Blog Post -->
        <div class="card mb-4">
            <div class="card-body">
                <h2 class="card-title">{% block text-title %}{% endblock text-title %}</h2>
                <p class="card-text">{% block content %}{% endblock content %}</p>
                <!--<a href="" class="btn btn-primary">Read More</a>-->
            </div>
            <div class="card-footer text-muted">
                Last Updated on {% block date %}{% endblock date %}
                <!--by-->
                <!--<a href="#">xxx</a>-->
            </div>
        </div>
        </div>
    </div>
    <!-- /.row -->
</div>
<!-- /.container -->
{% include 'info/layout/footer.html'%}
{% block extra_script %}{% endblock extra_script %}
<!-- -->
</body>
</html>

apps/info/templates/info/layout/footer.html
{% load static %}
<!-- Footer -->
<!--<footer class="py-2 bg-dark">-->
    <!--<div class="container">-->
        <!--<p class="m-0 text-center text-white">Copyright &copy; Amaceh & Bisma 2018</p>-->
    <!--</div>-->
    <!--&lt;!&ndash; /.container &ndash;&gt;-->
<!--</footer>-->


<!-- jQuery CDN -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<!-- jQuery local fallback -->
<script>
    window.jQuery || document.write('<script src="{% static 'info/bootstrap/js/jquery-3.3.1.slim.min.js' %}"><\/script>')
</script>
<!-- Bootstrap JS CDN -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" 
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
<!-- Bootstrap JS local fallback -->
<script>
    if(typeof($.fn.modal) === 'undefined') {document.write('<script src="{% static 'info/bootstrap/js/bootstrap.min.js' %}"><\/script>')}
</script>
<!-- Bootstrap CSS local fallback -->
<div id="bootstrapCssTest" class="hidden"></div>
<script>
    $(function() {
    //   if ($('#bootstrapCssTest').is(':visible')) {
      if(! $.fn.modal){
        $("head").prepend('<link rel="stylesheet" href="{% static 'info/bootstrap/css/bootstrap.min.css' %}">');
      }
    });

</script>

apps/info/templates/info/layout/header.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">
{% load static %}
<!-- Custom styles for this template -->
<link rel="stylesheet" type="text/css" href="{% static 'info/style.css' %}"/>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="SIMPUL DAPEN TELKOM">
<meta name="author" content="Achmad Abdul Rofiq & Bisma Wahyu">

apps/info/templates/info/layout/navbar.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'info:index' %}">SIMPUL DAPEN TELKOM - API</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'info:index' %}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <!--<li class="nav-item">-->
                    <!--<a class="nav-link" href="#">Services</a>-->
                <!--</li>-->
                <!--<li class="nav-item">-->
                    <!--<a class="nav-link" href="#">Contact</a>-->
                <!--</li>-->
            </ul>
        </div>
    </div>
</nav>